# Base configs
baseurl: "https://photos.dcasati.net"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photos by Diego Casati"
subtitle: "Random pictures"
author: "Diego Casati"
header:
 title: "Photos"
 subtitle: "by Diego Casati"
footer:
 name: "Hi, I'm Diego"
 bio: "These are some random photos I took while out with my camera. Enjoy !"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/diegocasati"
  instagram: "https://www.instagram.com/dcasati1"
  linkedin: "https://ca.linkedin.com/in/diegocasati"
  github: "https://www.github.com/dcasati"
